# Generated by Django 4.2.16 on 2025-01-14 16:56

import compass.documents.models
import cto_tool.storages
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mvp.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mvp", "0133_repositorycommit_shredded"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(
                        storage=cto_tool.storages.get_s3_storage,
                        upload_to=compass.documents.models.document_upload_to,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mvp.organization",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(mvp.mixins.PublicIdMixin, models.Model),
        ),
    ]
