version: 2
updates:
  - package-ecosystem: "uv" # uv support status https://github.com/astral-sh/uv/issues/2512
    open-pull-requests-limit: 1
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    ignore:
      # Do not update majors automatically
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      # Ignore patches to reduce noise
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
      # How to ignore something https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/controlling-dependencies-updated#ignoring-specific-dependencies
      # Ignore example 1
      - dependency-name: "example-depecndency*"
      # Ignore example 2
      - dependency-name: "example-depecndency-2*"
        versions: [">=1.0.0", "1.1.1"]
    groups:
      python-deps:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    open-pull-requests-limit: 1
    directory: "/vue-frontend"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    ignore:
      # Do not update majors automatically
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      # Ignore patches to reduce noise
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    groups:
      npm-deps:
        patterns:
          - "*"
  - package-ecosystem: "docker"
    open-pull-requests-limit: 1
    directory: "/build/cto-tool/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    ignore:
      # Do not update majors automatically
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      # Ignore patches to reduce noise
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    groups:
      docker-deps:
        patterns:
          - "*"
