# Generated by Django 4.2.16 on 2025-01-29 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mvp", "0134_organization_compass_enabled_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("prompt", models.TextField(blank=True, null=True)),
                ("result", models.JSONField(blank=True, default=None, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("complete", "Complete"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=100,
                    ),
                ),
                ("is_rollback", models.BooleanField(default=False)),
                ("is_reset", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mvp.organization",
                    ),
                ),
                (
                    "rollback_chat",
                    models.ForeignKey(
                        blank=True,
                        help_text="Used to rollback changes",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.chathistory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "chat histories",
            },
        ),
        migrations.AddConstraint(
            model_name="chathistory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("organization",),
                name="unique_active_chat_history_per_organization",
            ),
        ),
    ]
