# Generated by Django 4.2.4 on 2023-08-24 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('industry', models.CharField(choices=[('Govtech', 'Govtech'), ('Healthtech', 'Healthtech'), ('General Business Software', 'General Business Software'), ('Consumer Software', 'Consumer Software'), ('Tech-enabled services company', 'Tech-enabled services company'), ('Manufacturer', 'Manufacturer'), ('Other', 'Other')], max_length=50)),
                ('avg_developer_cost', models.PositiveIntegerField(verbose_name='Average developer yearly cost (including benefits), in $US')),
                ('num_developers', models.PositiveIntegerField(verbose_name='Number of current developers')),
                ('num_code_lines', models.PositiveIntegerField(verbose_name='Number of lines of code')),
                ('foundation_year', models.DateField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='dataproviderproject',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='customuser',
            name='organizations',
            field=models.ManyToManyField(to='mvp.organization'),
        ),
        migrations.AddField(
            model_name='dataproviderproject',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mvp.organization'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='dataproviderproject',
            unique_together={('organization', 'provider', 'external_id')},
        ),
    ]
