# Generated by Django 4.2.4 on 2023-08-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0003_dataproviderconnection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencerecord',
            name='critical_risk',
        ),
        migrations.RemoveField(
            model_name='referencerecord',
            name='low_risk',
        ),
        migrations.RemoveField(
            model_name='referencerecord',
            name='medium_high_risk',
        ),
        migrations.AddField(
            model_name='referencerecord',
            name='code_high_risk',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='referencerecord',
            name='code_low_risk',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='referencerecord',
            name='code_medium_risk',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='referencerecord',
            name='cve_high_risk',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='referencerecord',
            name='cyber_security_high_risk',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='referencerecord',
            name='open_source_medium_high_file_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='referencerecord',
            name='open_source_medium_high_package_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='referencerecord',
            name='commit_change_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='referencerecord',
            name='development_activity_change_rate',
            field=models.IntegerField(default=0),
        ),
    ]
