# Generated by Django 4.2.4 on 2023-08-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0004_remove_referencerecord_critical_risk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataproviderproject',
            name='meta',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
