# Generated by Django 4.2.4 on 2023-09-04 12:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0006_userinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='all_time_developers',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of all time developers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='first_commit_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of the first commit'),
            preserve_default=False,
        ),
    ]
