# Generated by Django 4.2.4 on 2023-09-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0007_organization_all_time_developers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataprovider',
            name='module',
            field=models.CharField(choices=[('Code Quality', 'Code Quality'), ('Process', 'Process'), ('Team', 'Team'), ('Open Source', 'Open Source'), ('Code Security', 'Code Security'), ('Cyber Security', 'Cyber Security')], default='Code Quality', max_length=30),
            preserve_default=False,
        ),
    ]
