# Generated by Django 4.2.4 on 2023-09-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0008_dataprovider_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataproviderconnection',
            name='last_fetched_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
