# Generated by Django 4.2.4 on 2023-09-15 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0009_dataproviderconnection_last_fetched_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='foundation_year',
        ),
    ]
