# Generated by Django 4.2.4 on 2023-09-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0010_remove_organization_foundation_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubModuleMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_module', models.CharField(choices=[('In-File Security', 'In-File Security'), ('Third-Party Security', 'Third-Party Security')], max_length=50)),
                ('metric', models.CharField(max_length=100)),
                ('percentile', models.PositiveIntegerField(default=0)),
                ('segment', models.CharField(choices=[('Enterprise-level', 'Enterprise-level'), ('Giants', 'Giants'), ('Growth', 'Growth'), ('Mature', 'Mature'), ('Mid-sized', 'Mid-sized'), ('Small Established', 'Small Established'), ('Young with big codebase', 'Young with big codebase'), ('Young with small codebase', 'Young with small codebase')], max_length=30)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
            options={
                'unique_together': {('sub_module', 'segment', 'metric', 'percentile')},
            },
        ),
    ]
