# Generated by Django 4.2.4 on 2023-09-29 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0011_submodulemetric'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('compliance_score', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('product_score', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('sema_score', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvp.organization')),
            ],
        ),
    ]
