# Generated by Django 4.2.4 on 2023-09-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0012_scorerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='all_time_developers',
            field=models.PositiveIntegerField(default=10, verbose_name='Number of all time developers'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='avg_developer_cost',
            field=models.PositiveIntegerField(default=100000, verbose_name='Average developer yearly cost (including benefits), in $US'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='first_commit_date',
            field=models.DateField(default='2020-01-01', verbose_name='Date of the first commit'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='industry',
            field=models.CharField(choices=[('Govtech', 'Govtech'), ('Healthtech', 'Healthtech'), ('General Business Software', 'General Business Software'), ('Consumer Software', 'Consumer Software'), ('Tech-enabled services company', 'Tech-enabled services company'), ('Manufacturer', 'Manufacturer'), ('Other', 'Other')], default=('Govtech', 'Govtech'), max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='num_code_lines',
            field=models.PositiveIntegerField(default=1000, verbose_name='Number of lines of code'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='num_developers',
            field=models.PositiveIntegerField(default=10, verbose_name='Number of current developers'),
        ),
    ]
