# Generated by Django 4.2.4 on 2023-10-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0013_alter_organization_all_time_developers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submodulemetric',
            name='metric',
            field=models.CharField(choices=[('high_risk_in_file', 'High_Risk_In_File'), ('high_risk_cves', 'High_Risk_CVEs')], max_length=100),
        ),
    ]
