# Generated by Django 4.2.4 on 2023-10-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0014_alter_submodulemetric_metric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submodulemetric',
            name='metric',
            field=models.CharField(choices=[('cyber_security_evaluation', 'cyber_security_evaluation'), ('high_risk_in_file', 'High_Risk_In_File'), ('high_risk_cves', 'High_Risk_CVEs')], max_length=100),
        ),
        migrations.AlterField(
            model_name='submodulemetric',
            name='sub_module',
            field=models.CharField(choices=[('Cyber Security Evaluation', 'Cyber Security Evaluation'), ('In-File Security', 'In-File Security'), ('Third-Party Security', 'Third-Party Security')], max_length=50),
        ),
    ]
