# Generated by Django 4.2.4 on 2023-10-16 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0017_alter_submodulemetric_metric_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='first_commit_date',
            field=models.DateField(default=datetime.date(2020, 1, 1), verbose_name='Date of the first commit'),
        ),
    ]
