# Generated by Django 4.2.4 on 2023-10-18 12:24

from django.db import migrations
import mvp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0018_alter_organization_first_commit_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataprovider',
            name='module',
        ),
        migrations.AddField(
            model_name='dataprovider',
            name='modules',
            field=mvp.models.ModuleChoicesField(default=list),
        ),
    ]
