# Generated by Django 4.2.4 on 2023-10-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0019_remove_dataprovider_module_dataprovider_modules'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('short_name', models.CharField(max_length=100, unique=True)),
                ('spdx', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Commercial', 'Commercial'), ('Copyleft', 'Copyleft'), ('Copyleft Limited', 'Copyleft Limited'), ('Free Restricted', 'Free Restricted'), ('Permissive', 'Permissive'), ('Proprietary Free', 'Proprietary Free'), ('Public Domain', 'Public Domain'), ('Source-available', 'Source-available'), ('Unstated License', 'Unstated License'), ('Grand Total', 'Grand Total')], max_length=30)),
            ],
        ),
    ]
