# Generated by Django 4.2.4 on 2023-10-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0020_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvitation',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
