# Generated by Django 4.2.4 on 2023-10-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0021_userinvitation_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='num_code_lines',
            field=models.PositiveIntegerField(blank=True, default=1000, null=True, verbose_name='Number of lines of code'),
        ),
        migrations.AlterField(
            model_name='submodulemetric',
            name='metric',
            field=models.CharField(choices=[('cyber_security_evaluation', 'cyber_security_evaluation'), ('developers_retention_ratio', 'developers_retention_ratio'), ('high_risk_in_file', 'High_Risk_In_File'), ('high_risk_cves', 'High_Risk_CVEs'), ('in_reference_risk_count', 'in_reference_risk_count'), ('unit_testing_ratio', 'unit_testing_ratio')], max_length=100),
        ),
        migrations.AlterField(
            model_name='submodulemetric',
            name='sub_module',
            field=models.CharField(choices=[('Cyber Security Evaluation', 'Cyber Security Evaluation'), ('Developers Retention Ratio', 'Developers Retention Ratio'), ('In-File Security', 'In-File Security'), ('In-Reference Risk', 'In-Reference Risk'), ('Third-Party Security', 'Third-Party Security'), ('Unit Testing Ratio', 'Unit Testing Ratio')], max_length=50),
        ),
    ]
