# Generated by Django 4.2.4 on 2023-10-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0023_alter_customuser_options_customuser_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppComponentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.CharField(choices=[('sema_score', 'Sema Score')], max_length=50)),
                ('version', models.PositiveIntegerField()),
            ],
            options={
                'unique_together': {('component', 'version')},
            },
        ),
    ]
