# Generated by Django 4.2.4 on 2023-11-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0024_appcomponentversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('active_developer', 'active_developer'), ('average_developer_activity', 'average_developer_activity'), ('average_developer_activity_evaluation', 'average_developer_activity_evaluation'), ('byte_count', 'byte_count'), ('commit_analysis_evaluation', 'commit_analysis_evaluation'), ('cyber_security_dark_web_botnet_evaluation', 'cyber_security_dark_web_botnet_evaluation'), ('cyber_security_email_risk_evaluation', 'cyber_security_email_risk_evaluation'), ('cyber_security_evaluation', 'cyber_security_evaluation'), ('cyber_security_leaked_credentials_evaluation', 'cyber_security_leaked_credentials_evaluation'), ('cyber_security_web_or_cred_evaluation', 'cyber_security_web_or_cred_evaluation'), ('developers_and_development_activity_evaluation', 'developers_and_development_activity_evaluation'), ('developers_retention_ratio', 'developers_retention_ratio'), ('groups_percentage_with_high_retention', 'groups_percentage_with_high_retention'), ('high_risk_cves', 'high_risk_cves'), ('high_risk_in_file', 'high_risk_in_file'), ('in_file_high_risk_count', 'in_file_high_risk_count'), ('in_file_medium_high_risk_count', 'in_file_medium_high_risk_count'), ('in_file_risk_count', 'in_file_risk_count'), ('in_house_current_test_ratio', 'in_house_current_test_ratio'), ('in_reference_risk_count', 'in_reference_risk_count'), ('infile_to_cves_ratio', 'infile_to_cves_ratio'), ('infile_to_reference_ratio', 'infile_to_reference_ratio'), ('lines_of_code', 'lines_of_code'), ('organization_count', 'organization_count'), ('organization_count_with_cyber_security_eval', 'organization_count_with_cyber_security_eval'), ('package_manager_high_risk_count', 'package_manager_high_risk_count'), ('package_manager_medium_high_risk_count', 'package_manager_medium_high_risk_count'), ('percentage_with_high_retention', 'percentage_with_high_retention'), ('repos_percentage_with_high_retention', 'repos_percentage_with_high_retention'), ('third_party_risk_count', 'third_party_risk_count'), ('total_commits', 'total_commits'), ('total_repositories', 'total_repositories'), ('total_commiters', 'total_commiters')], max_length=100)),
                ('percentile', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('segment', models.CharField(choices=[('Enterprise-level', 'Enterprise-level'), ('Giants', 'Giants'), ('Growth', 'Growth'), ('Mature', 'Mature'), ('Mid-sized', 'Mid-sized'), ('Small Established', 'Small Established'), ('Young with big codebase', 'Young with big codebase'), ('Young with small codebase', 'Young with small codebase')], max_length=30)),
                ('value', models.DecimalField(decimal_places=12, default=0, max_digits=24)),
            ],
            options={
                'unique_together': {('metric', 'percentile', 'segment')},
            },
        ),
        migrations.DeleteModel(
            name='SubModuleMetric',
        ),
    ]
