# Generated by Django 4.2.4 on 2023-11-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0025_referencemetric_delete_submodulemetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvitation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinvitation',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
