# Generated by Django 4.2.4 on 2023-11-12 05:07

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0026_userinvitation_deleted_at_userinvitation_is_deleted'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userinvitation',
            managers=[
                ('global_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
