# Generated by Django 4.2.4 on 2023-11-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0027_alter_userinvitation_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
