# Generated by Django 4.2.4 on 2023-11-14 04:57

from django.db import migrations


def populate_jurisdiction(apps, schema_editor):
    Jurisdiction = apps.get_model("mvp", "Jurisdiction")

    initial_values = ["USA", "California", "EU", "UK", "China"]
    for value in initial_values:
        Jurisdiction.objects.create(name=value)


class Migration(migrations.Migration):
    dependencies = [
        ("mvp", "0028_jurisdiction"),
    ]

    operations = [
        migrations.RunPython(populate_jurisdiction),
    ]
