# Generated by Django 4.2.4 on 2023-11-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0029_populate_jurisdiction'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='jurisdictions_customers',
            field=models.ManyToManyField(blank=True, related_name='jurisdictions_customers', to='mvp.jurisdiction'),
        ),
        migrations.AddField(
            model_name='organization',
            name='jurisdictions_developers',
            field=models.ManyToManyField(blank=True, related_name='jurisdictions_developers', to='mvp.jurisdiction'),
        ),
        migrations.AddField(
            model_name='organization',
            name='jurisdictions_headquarters',
            field=models.ManyToManyField(blank=True, related_name='jurisdictions_headquarters', to='mvp.jurisdiction'),
        ),
    ]
