# Generated by Django 4.2.4 on 2023-11-14 07:59

from django.db import migrations


def populate_industry(apps, schema_editor):
    Industry = apps.get_model("mvp", "Industry")
    Organization = apps.get_model("mvp", "Organization")

    initial_values = [
        "Govtech",
        "Healthtech",
        "General Business Software",
        "Consumer Software",
        "Tech-enabled services company",
        "Manufacturer",
        "Other",
    ]
    industry_mapping = {}
    for value in initial_values:
        industry_mapping[value] = Industry.objects.create(name=value)

    for organization in Organization.objects.all():
        if organization.industry not in industry_mapping:
            continue

        organization.industry_new = industry_mapping[organization.industry]
        organization.save()


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("mvp", "0031_industry_organization_industry_new"),
    ]

    operations = [
        migrations.RunPython(populate_industry),
    ]
