# Generated by Django 4.2.4 on 2023-11-14 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mvp", "0032_populate_industry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="industry",
        ),
        migrations.RenameField(
            model_name="organization",
            old_name="industry_new",
            new_name="industry",
        ),
    ]
