# Generated by Django 4.2.4 on 2023-11-14 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0033_remove_organization_industry_new_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('regulation_status', models.CharField(choices=[('proposed', 'Proposed'), ('under_discussion', 'Under Discussion'), ('near_final', 'Near Final'), ('final_but_not_implemented', 'Final but not Implemented'), ('final_and_implemented', 'Final and Implemented'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], max_length=30)),
                ('industries_customers', models.ManyToManyField(blank=True, related_name='industries_customers', to='mvp.industry')),
                ('jurisdictions_customers', models.ManyToManyField(blank=True, related_name='compliance_jurisdictions_customers', to='mvp.jurisdiction')),
                ('jurisdictions_developers', models.ManyToManyField(blank=True, related_name='compliance_jurisdictions_developers', to='mvp.jurisdiction')),
                ('jurisdictions_headquarters', models.ManyToManyField(blank=True, related_name='compliance_jurisdictions_headquarters', to='mvp.jurisdiction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='organization',
            name='jurisdictions_customers',
            field=models.ManyToManyField(blank=True, related_name='organization_jurisdictions_customers', to='mvp.jurisdiction'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='jurisdictions_developers',
            field=models.ManyToManyField(blank=True, related_name='organization_jurisdictions_developers', to='mvp.jurisdiction'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='jurisdictions_headquarters',
            field=models.ManyToManyField(blank=True, related_name='organization_jurisdictions_headquarters', to='mvp.jurisdiction'),
        ),
        migrations.CreateModel(
            name='ComplianceStandardComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('rules', models.JSONField(blank=True, default=None, null=True)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvp.compliancestandard')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
