# Generated by Django 4.2.4 on 2023-11-14 08:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0034_compliancestandard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='industry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
