# Generated by Django 4.2.4 on 2023-11-15 07:22

from django.db import migrations, models
import django.db.models.deletion
import mvp.mixins


class Migration(migrations.Migration):
    dependencies = [
        ("mvp", "0035_industry_created_at_industry_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("production", "Production"),
                            ("production-legacy", "Production-Legacy"),
                            ("internal-tools", "InternalTools"),
                            ("development", "Development"),
                        ],
                        default=None,
                        max_length=50,
                        null=True,
                    ),
                ),
                ("code_size", models.PositiveIntegerField(default=0)),
                ("code_ai_size", models.PositiveIntegerField(default=0)),
                (
                    "code_ai_likelihood",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mvp.organization",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mvp.dataprovider",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "repositories",
                "unique_together": {("organization", "provider", "name")},
            },
            bases=(mvp.mixins.PublicIdMixin, models.Model),
        ),
        migrations.CreateModel(
            name="RepositorySnippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file_path", models.CharField(max_length=500)),
                ("line_number_start", models.PositiveIntegerField(default=0)),
                ("line_number_end", models.PositiveIntegerField(default=0)),
                ("code_size", models.PositiveIntegerField(default=0)),
                ("code_ai_size", models.PositiveIntegerField(default=0)),
                (
                    "code_ai_likelihood",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mvp.repository"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
