# Generated by Django 4.2.4 on 2023-11-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0036_repository_repositorysnippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='ai_code_monitor_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
