# Generated by Django 4.2.4 on 2023-11-16 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0037_organization_ai_code_monitor_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceStandardLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvp.compliancestandard')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
