# Generated by Django 4.2.4 on 2023-11-20 10:20

from django.db import migrations
import mvp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0039_compliancestandardcomponent_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancestandardcomponent',
            name='ai_types',
            field=mvp.models.AITypeChoicesField(default=list),
        ),
    ]
