# Generated by Django 4.2.4 on 2023-11-22 11:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mvp", "0040_compliancestandardcomponent_ai_types"),
    ]

    operations = [
        migrations.RenameField(
            model_name="repository",
            old_name="code_ai_likelihood",
            new_name="code_ai_score",
        ),
        migrations.RenameField(
            model_name="repositorysnippet",
            old_name="code_ai_likelihood",
            new_name="code_ai_score",
        ),
    ]
