# Generated by Django 4.2.4 on 2023-11-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0041_rename_code_ai_likelihood_repository_code_ai_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositorysnippet',
            name='code_ai_score_label',
            field=models.CharField(blank=True, choices=[('ai', 'AI'), ('human', 'Human')], default=None, max_length=20, null=True),
        ),
    ]
