# Generated by Django 4.2.4 on 2023-11-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0042_repositorysnippet_code_ai_score_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancestandardcomponent',
            name='name',
            field=models.CharField(default='Name placeholder', max_length=100),
            preserve_default=False,
        ),
    ]
