# Generated by Django 4.2.4 on 2023-11-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0043_alter_compliancestandardcomponent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='cto_dashboard_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
