# Generated by Django 4.2.4 on 2023-11-30 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0044_organization_cto_dashboard_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='last_commit_sha',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='industry',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mvp.industry'),
        ),
    ]
