# Generated by Django 4.2.4 on 2023-11-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0045_repository_last_commit_sha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='owner',
            field=models.CharField(default='owner', max_length=100),
            preserve_default=False,
        ),
    ]
