# Generated by Django 4.2.4 on 2023-11-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0046_repository_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='last_analysis_file',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
