# Generated by Django 4.2.4 on 2023-11-30 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0047_repository_last_analysis_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together={('organization', 'provider', 'owner', 'name')},
        ),
    ]
