# Generated by Django 4.2.4 on 2023-11-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0049_repository_last_analysis_num_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='code_ai_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
