# Generated by Django 4.2.4 on 2023-12-04 06:49

from django.db import migrations


def empty_repositories(apps, schema_editor):
    Repository = apps.get_model("mvp", "Repository")
    Repository.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("mvp", "0050_repository_code_ai_percentage"),
    ]

    operations = [
        migrations.RunPython(empty_repositories),
    ]
