# Generated by Django 4.2.4 on 2023-12-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0051_empty_repositories'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='repository',
            name='external_id',
            field=models.CharField(default='external_id', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together={('organization', 'provider', 'external_id')},
        ),
    ]
