# Generated by Django 4.2.4 on 2023-12-04 07:24

from django.db import migrations


def empty_repository_snippets(apps, schema_editor):
    RepositorySnippet = apps.get_model("mvp", "RepositorySnippet")
    RepositorySnippet.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("mvp", "0052_alter_repository_unique_together_and_more"),
    ]

    operations = [
        migrations.RunPython(empty_repository_snippets),
    ]
