# Generated by Django 4.2.4 on 2023-12-04 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0053_empty_repository_snippets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repositorysnippet',
            name='repository',
        ),
        migrations.CreateModel(
            name='RepositoryCommit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sha', models.CharField(max_length=40)),
                ('date_time', models.DateTimeField()),
                ('code_size', models.PositiveIntegerField(default=0)),
                ('code_ai_size', models.PositiveIntegerField(default=0)),
                ('code_ai_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('code_ai_score', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('analysis_file', models.TextField(blank=True, default=None, null=True)),
                ('analysis_num_files', models.PositiveIntegerField(default=0)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvp.repository')),
            ],
            options={
                'unique_together': {('repository', 'sha')},
            },
        ),
        migrations.AddField(
            model_name='repositorysnippet',
            name='commit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mvp.repositorycommit'),
            preserve_default=False,
        ),
    ]
