# Generated by Django 4.2.4 on 2023-12-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0054_remove_repositorysnippet_repository_repositorycommit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='code_ai_size',
            new_name='code_ai_num_lines',
        ),
        migrations.RenameField(
            model_name='repository',
            old_name='code_size',
            new_name='code_num_lines',
        ),
        migrations.RenameField(
            model_name='repositorycommit',
            old_name='code_ai_size',
            new_name='code_ai_num_lines',
        ),
        migrations.RenameField(
            model_name='repositorycommit',
            old_name='code_size',
            new_name='code_num_lines',
        ),
        migrations.RenameField(
            model_name='repositorysnippet',
            old_name='code_ai_size',
            new_name='code_ai_num_lines',
        ),
        migrations.RenameField(
            model_name='repositorysnippet',
            old_name='line_number_end',
            new_name='code_line_end',
        ),
        migrations.RenameField(
            model_name='repositorysnippet',
            old_name='line_number_start',
            new_name='code_line_start',
        ),
        migrations.RenameField(
            model_name='repositorysnippet',
            old_name='code_size',
            new_name='code_num_lines',
        ),
        migrations.AddField(
            model_name='repositorysnippet',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
