# Generated by Django 4.2.4 on 2023-12-14 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0055_rename_code_ai_size_repository_code_ai_num_lines_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvp.organization')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvp.dataprovider')),
            ],
            options={
                'unique_together': {('organization', 'provider', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='RepositoryAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_num_lines', models.PositiveIntegerField(default=0)),
                ('code_ai_num_lines', models.PositiveIntegerField(default=0)),
                ('code_ai_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('code_ai_score', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvp.author')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvp.repository')),
            ],
            options={
                'unique_together': {('repository', 'author')},
            },
        ),
        migrations.CreateModel(
            name='RepositoryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_path', models.CharField(max_length=500)),
                ('code_num_lines', models.PositiveIntegerField(default=0)),
                ('code_ai_num_lines', models.PositiveIntegerField(default=0)),
                ('code_ai_score', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('code_ai_score_label', models.CharField(blank=True, choices=[('ai', 'AI'), ('blended', 'Blended'), ('human', 'Human')], default=None, max_length=20, null=True)),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvp.repositorycommit')),
            ],
            options={
                'unique_together': {('commit', 'file_path')},
            },
        ),
        migrations.CreateModel(
            name='RepositoryFileBlame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sha', models.CharField(max_length=40)),
                ('date_time', models.DateTimeField()),
                ('code_line_start', models.PositiveIntegerField(default=0)),
                ('code_line_end', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvp.author')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvp.repositoryfile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RepositoryFileChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code_line_start', models.PositiveIntegerField(default=0)),
                ('code_line_end', models.PositiveIntegerField(default=0)),
                ('code_num_lines', models.PositiveIntegerField(default=0)),
                ('code_ai_num_lines', models.PositiveIntegerField(default=0)),
                ('code_ai_score', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('code_ai_score_label', models.CharField(blank=True, choices=[('ai', 'AI'), ('blended', 'Blended'), ('human', 'Human')], default=None, max_length=20, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvp.repositoryfile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='RepositorySnippet',
        ),
    ]
