# Generated by Django 4.2.4 on 2023-12-15 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0056_author_repositoryauthor_repositoryfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='installation_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
