# Generated by Django 4.2.4 on 2023-12-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0057_repository_installation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='code_ai_blended_num_lines',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repository',
            name='code_ai_blended_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='repository',
            name='code_ai_pure_num_lines',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repository',
            name='code_ai_pure_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='repositoryauthor',
            name='code_ai_blended_num_lines',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repositoryauthor',
            name='code_ai_blended_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='repositoryauthor',
            name='code_ai_pure_num_lines',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repositoryauthor',
            name='code_ai_pure_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='repositorycommit',
            name='code_ai_blended_num_lines',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repositorycommit',
            name='code_ai_blended_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='repositorycommit',
            name='code_ai_pure_num_lines',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repositorycommit',
            name='code_ai_pure_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='repositoryfile',
            name='code_ai_blended_num_lines',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repositoryfile',
            name='code_ai_pure_num_lines',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
