# Generated by Django 4.2.4 on 2023-12-19 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0058_repository_code_ai_blended_num_lines_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositorycommit',
            name='analyzed',
            field=models.BooleanField(default=False),
        ),
    ]
