# Generated by Django 4.2.4 on 2024-01-09 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mvp", "0059_repositorycommit_analyzed"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="connection_issued_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="first_analysis_done",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
