# Generated by Django 4.2.4 on 2024-01-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mvp", "0060_organization_connection_issued_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="first_analysis_done",
            field=models.BooleanField(default=False),
        ),
    ]
