# Generated by Django 4.2.4 on 2024-01-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mvp", "0061_alter_organization_first_analysis_done"),
    ]

    def set_status_to_analyzed(apps, schema_editor):
        RepositoryCommit = apps.get_model("mvp", "RepositoryCommit")
        # Set the 'status' field to 'analyzed' where 'analyzed' field is True
        RepositoryCommit.objects.filter(analyzed=True).update(status="analyzed")

    def revert_status_to_analyzed(apps, schema_editor):
        RepositoryCommit = apps.get_model("mvp", "RepositoryCommit")
        # Set the 'analyzed' field to True where 'status' field is 'analyzed'
        RepositoryCommit.objects.filter(status="analyzed").update(analyzed=True)

    operations = [
        migrations.AddField(
            model_name="repositorycommit",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("analyzed", "Analyzed"),
                    ("failure", "Failure"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.RunPython(
            code=set_status_to_analyzed,
            reverse_code=revert_status_to_analyzed,
        ),
        migrations.RemoveField(
            model_name="repositorycommit",
            name="analyzed",
        ),
    ]
