# Generated by Django 4.2.4 on 2024-01-12 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0062_remove_repositorycommit_analyzed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='code_ai_score',
            new_name='code_generation_score',
        ),
        migrations.RenameField(
            model_name='repositoryauthor',
            old_name='code_ai_score',
            new_name='code_generation_score',
        ),
        migrations.RenameField(
            model_name='repositorycommit',
            old_name='code_ai_score',
            new_name='code_generation_score',
        ),
        migrations.RenameField(
            model_name='repositoryfile',
            old_name='code_ai_score_label',
            new_name='code_generation_label',
        ),
        migrations.RenameField(
            model_name='repositoryfile',
            old_name='code_ai_score',
            new_name='code_generation_score',
        ),
        migrations.RenameField(
            model_name='repositoryfilechunk',
            old_name='code_ai_score_label',
            new_name='code_generation_label',
        ),
        migrations.RenameField(
            model_name='repositoryfilechunk',
            old_name='code_ai_score',
            new_name='code_generation_score',
        ),
    ]
