# Generated by Django 4.2.4 on 2024-01-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0063_rename_code_ai_score_repository_code_generation_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositoryfilechunk',
            name='code_generation_model_label',
            field=models.CharField(blank=True, choices=[('ai', 'AI'), ('blended', 'Blended'), ('human', 'Human')], default=None, max_length=20, null=True),
        ),
    ]
