# Generated by Django 4.2.4 on 2024-01-17 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0064_repositoryfilechunk_code_generation_model_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceStandardRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('condition_mode', models.CharField(choices=[('all', 'All'), ('any', 'Any'), ('none', 'None')], max_length=100)),
                ('risk', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='compliancestandardcomponent',
            name='rules',
        ),
        migrations.CreateModel(
            name='ComplianceStandardRuleCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_type', models.CharField(choices=[('ai', 'GenAI'), ('pure', 'GenAI Pure'), ('blended', 'GenAI Blended'), ('human', 'Human')], max_length=100)),
                ('operator', models.CharField(choices=[('=', 'Equal to'), ('>', 'Greater than'), ('>=', 'Greater than or Equal to'), ('<', 'Less than'), ('<=', 'Less than or Equal to')], max_length=100)),
                ('percentage', models.PositiveIntegerField(default=0)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvp.compliancestandardrule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='compliancestandardcomponent',
            name='rules',
            field=models.ManyToManyField(blank=True, related_name='compliance_standard_rules', to='mvp.compliancestandardrule'),
        ),
    ]
