# Generated by Django 4.2.4 on 2024-01-17 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0065_compliancestandardrule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancestandardrulecondition',
            name='operator',
            field=models.CharField(choices=[('>', 'Greater than'), ('>=', 'Greater than or Equal to'), ('=', 'Equal to'), ('<=', 'Less than or Equal to'), ('<', 'Less than')], max_length=100),
        ),
        migrations.AlterField(
            model_name='compliancestandardrulecondition',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='mvp.compliancestandardrule'),
        ),
    ]
