# Generated by Django 4.2.4 on 2024-01-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0066_alter_compliancestandardrulecondition_operator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataproviderproject',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
