# Generated by Django 4.2.4 on 2024-01-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0067_alter_dataproviderproject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancestandardrulecondition',
            name='code_type',
            field=models.CharField(choices=[('ai', 'GenAI'), ('pure', 'GenAI Pure'), ('blended', 'GenAI Blended'), ('human', 'NotGenAI')], max_length=100),
        ),
        migrations.AlterField(
            model_name='repositoryfile',
            name='code_generation_label',
            field=models.CharField(blank=True, choices=[('ai', 'AI'), ('blended', 'Blended'), ('human', 'NotGenAI')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='repositoryfilechunk',
            name='code_generation_label',
            field=models.CharField(blank=True, choices=[('ai', 'AI'), ('blended', 'Blended'), ('human', 'NotGenAI')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='repositoryfilechunk',
            name='code_generation_model_label',
            field=models.CharField(blank=True, choices=[('ai', 'AI'), ('blended', 'Blended'), ('human', 'NotGenAI')], default=None, max_length=20, null=True),
        ),
    ]
