# Generated by Django 4.2.4 on 2024-01-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0069_repository_languages_repositoryfile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoryfile',
            name='language',
            field=models.CharField(blank=True, choices=[('abap', 'ABAP'), ('ada', 'Ada'), ('arduino', 'Arduino'), ('assembly', 'Assembly'), ('bash', 'Bash'), ('basic', 'Basic'), ('c', 'C'), ('cpp', 'C++'), ('csharp', 'C#'), ('clojure', 'Clojure'), ('cobol', 'Cobol'), ('coffeeScript', 'CoffeeScript'), ('cuda', 'Cuda'), ('d', 'D'), ('dart', 'Dart'), ('delphi', 'Delphi'), ('eiffel', 'Eiffel'), ('elixir', 'Elixir'), ('elm', 'Elm'), ('erlang', 'Erlang'), ('fsharp', 'F#'), ('forth', 'Forth'), ('fortran', 'Fortran'), ('go', 'Go'), ('groovy', 'Groovy'), ('haskell', 'Haskell'), ('html', 'HTML'), ('java', 'Java'), ('javascript', 'JavaScript'), ('j', 'J'), ('julia', 'Julia'), ('kotlin', 'Kotlin'), ('labview', 'LabView'), ('lisp', 'Lisp'), ('logic', 'Logic'), ('lua', 'Lua'), ('mathematica', 'Mathematica'), ('matlab', 'Matlab'), ('ocaml', 'OCaml'), ('perl', 'Perl'), ('php', 'PHP'), ('prolog', 'Prolog'), ('python', 'Python'), ('raku', 'Raku'), ('r', 'R'), ('rb', 'Ruby'), ('rust', 'Rust'), ('sas', 'SAS'), ('scala', 'Scala'), ('scheme', 'Scheme'), ('sql', 'SQL'), ('swift', 'Swift'), ('tcl', 'TCL'), ('tsx', 'TypeScript'), ('typescript', 'TypeScript'), ('unknown', 'Unknown'), ('vhdl', 'VHDL'), ('verilog', 'Verilog'), ('asm', 'WebAssembly')], default=None, max_length=12, null=True),
        ),
    ]
