# Generated by Django 4.2.4 on 2024-01-25 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mvp", "0070_alter_repositoryfile_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repository",
            name="category",
        ),
        migrations.CreateModel(
            name="RepositoryGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "usage_category",
                    models.CharField(
                        choices=[
                            ("production", "Production"),
                            ("production_legacy", "Production - Legacy"),
                            ("internal_tools", "Internal Tools"),
                            ("development", "Development"),
                            ("not_in_use", "Not in use"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "gen_ai_guidance",
                    models.CharField(
                        choices=[
                            ("blended_only", "Blended Code Only"),
                            ("no_restrictions", "No Restrictions"),
                            ("gen_ai_not_permitted", "Gen AI Code Not Permitted"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mvp.organization",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "organization")},
            },
        ),
        migrations.AddField(
            model_name="repository",
            name="group",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mvp.repositorygroup",
            ),
        ),
    ]
