# Generated by Django 4.2.4 on 2024-01-30 17:18

from django.db import migrations

countries = [
    "Australia",
    "Austria",
    "Baden-Württemberg",
    "Belgium",
    "Bulgaria",
    "California",
    "Canada",
    "Chile",
    "China",
    "Croatia",
    "Czech Republic",
    "Denmark",
    "Estonia",
    "EU",
    "Finland",
    "France",
    "Germany",
    "Greece",
    "Hungary",
    "India",
    "Ireland",
    "Israel",
    "Italy",
    "Japan",
    "Latvia",
    "Lithuania",
    "Luxembourg",
    "Malaysia",
    "Malta",
    "Netherlands",
    "New York",
    "Nigeria",
    "Poland",
    "Portugal",
    "Republic of Cyprus",
    "Romania",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Spain",
    "Sweden",
    "UK",
    "USA",
]


def delete_data(apps, schema_editor):
    Jurisdiction = apps.get_model("mvp", "Jurisdiction")
    for jurisdiction in Jurisdiction.objects.all():
        jurisdiction.delete()


def add_data(apps, schema_editor):
    Jurisdiction = apps.get_model("mvp", "Jurisdiction")
    for country in countries:
        jurisdiction = Jurisdiction.objects.create(name=country)
        jurisdiction.save()


class Migration(migrations.Migration):
    dependencies = [
        (
            "mvp",
            "0072_remove_compliancestandard_jurisdictions_customers_and_more__manual",
        ),
    ]

    operations = [
        migrations.RunPython(delete_data, add_data),
        migrations.DeleteModel(
            name="Jurisdiction",
        ),
    ]
