# Generated by Django 4.2.4 on 2024-01-31 15:59

from django.db import migrations

replacement_strings = [
    ("baden-württemberg", "baden-wurttemberg"),
]


def change_spelling(mode):
    if mode == "fix":
        replace_strs_data = {x: y for x, y in replacement_strings}
    elif mode == "unfix":
        replace_strs_data = {y: x for x, y in replacement_strings}

    def replace_str(key):
        return replace_strs_data.get(key, key)

    def replace_strings_in_jurisdictions(apps, schema_editor):
        Organization = apps.get_model("mvp", "Organization")
        ComplianceStandard = apps.get_model("mvp", "ComplianceStandard")

        for Model in [Organization, ComplianceStandard]:
            for model in Model.objects.all():
                # replace existing jurisdiction names with correct spellings
                jurisdictions_customers = list(
                    set(map(replace_str, model.jurisdictions_customers))
                )
                jurisdictions_developers = list(
                    set(map(replace_str, model.jurisdictions_developers))
                )
                jurisdictions_headquarters = list(
                    set(map(replace_str, model.jurisdictions_headquarters))
                )

                model.jurisdictions_customers = jurisdictions_customers
                model.jurisdictions_developers = jurisdictions_developers
                model.jurisdictions_headquarters = jurisdictions_headquarters

                model.save()

    return replace_strings_in_jurisdictions


class Migration(migrations.Migration):
    dependencies = [
        ("mvp", "0073_delete_jurisdiction"),
    ]

    operations = [
        migrations.RunPython(change_spelling("fix"), change_spelling("unfix"))
    ]
