# Generated by Django 4.2.4 on 2024-02-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0075_jurisdiction_key_changes__manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='analysis_max_lines_per_repository',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='analysis_max_repositories',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
