# Generated by Django 4.2.4 on 2024-02-23 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mvp", "0078_create_gen_ai_guidance_rules__manual"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repositorygroup",
            name="gen_ai_guidance",
        ),
    ]
