# Generated by Django 4.2.4 on 2024-02-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0079_remove_repositorygroup_gen_ai_guidance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoryfile',
            name='code_generation_label',
            field=models.CharField(blank=True, choices=[('ai', 'AI'), ('blended', 'Blended'), ('human', 'NotGenAI'), ('not_evaluated', 'NotEvaluated')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='repositoryfilechunk',
            name='code_generation_label',
            field=models.CharField(blank=True, choices=[('ai', 'AI'), ('blended', 'Blended'), ('human', 'NotGenAI'), ('not_evaluated', 'NotEvaluated')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='repositoryfilechunk',
            name='code_generation_model_label',
            field=models.CharField(blank=True, choices=[('ai', 'AI'), ('blended', 'Blended'), ('human', 'NotGenAI'), ('not_evaluated', 'NotEvaluated')], default=None, max_length=20, null=True),
        ),
    ]
