# Generated by Django 4.2.4 on 2024-02-27 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mvp", "0080_alter_repositoryfile_code_generation_label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="linked_author",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mvp.author",
            ),
        ),
    ]
