# Generated by Django 4.2.4 on 2024-02-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mvp", "0081_author_linked_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="not_evaluated_num_files",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
