# Generated by Django 4.2.4 on 2024-02-29 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0082_repository_not_evaluated_num_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryFileChunkBlame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sha', models.CharField(max_length=40)),
                ('date_time', models.DateTimeField()),
                ('code_line_start', models.PositiveIntegerField(default=0)),
                ('code_line_end', models.PositiveIntegerField(default=0)),
                ('code_generation_label', models.CharField(blank=True, choices=[('ai', 'AI'), ('blended', 'Blended'), ('human', 'NotGenAI'), ('not_evaluated', 'NotEvaluated')], default=None, max_length=20, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvp.author')),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvp.repositoryfilechunk')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
