# Generated by Django 4.2.4 on 2024-03-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0085_remove_repository_code_generation_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositoryfile',
            name='not_evaluated',
            field=models.BooleanField(default=False),
        ),
    ]
