# Generated by Django 4.2.4 on 2024-03-06 15:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mvp", "0086_repositoryfile_not_evaluated"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ComplianceStandardLink",
        ),
        migrations.DeleteModel(
            name="ComplianceStandardComponent",
        ),
        migrations.DeleteModel(
            name="ComplianceStandard",
        ),
    ]
