# Generated by Django 4.2.4 on 2024-03-12 12:02

from django.db import migrations, models
import django.db.models.deletion
import mvp.models


class Migration(migrations.Migration):
    dependencies = [
        ("mvp", "0087_delete_compliancestandard__manual"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceStandard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "external_id",
                    models.CharField(
                        blank=True, help_text="Unique ID", max_length=100, null=True
                    ),
                ),
                ("name", models.TextField()),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("critical", "1-Critical"),
                            ("high", "2-High"),
                            ("medium", "3-Medium"),
                            ("low", "4-Low"),
                            ("to_be_determined", "5-To be determined"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "remediation_mitigation",
                    models.TextField(
                        blank=True, null=True, verbose_name="Remediation/Mitigation"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("contemplated", "1-Contemplated"),
                            ("proposed", "2-Proposed"),
                            ("close_to_implementation", "3-Close to implementation"),
                            ("partially_in_effect", "4-Partially in effect"),
                            ("fully_implemented", "5-Fully implemented"),
                            ("to_be_determined", "6-To Be Determined"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("internal", "1-Internal"),
                            ("government", "2-Government"),
                            ("other_stakeholders", "3-Other stakeholders"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "risk_type",
                    models.CharField(
                        choices=[
                            ("strategic", "1-Strategic"),
                            ("operational", "2-Operational"),
                        ],
                        max_length=30,
                    ),
                ),
                ("sema_source", models.CharField(max_length=100)),
                (
                    "third_party_source_unique_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "policy_instrument_type_oecd",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "organization_size_oecd",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("any_size", "1-Firms of Any size"),
                            ("sme", "2-SMEs (10-249 Employees)"),
                            ("large", "3-Large Firms (250 Employees)"),
                            ("multinational", "4-Multinational Enterprises"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("is_excluded", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ComplianceStandardAIUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Geography",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "geographies",
            },
        ),
        migrations.CreateModel(
            name="ComplianceStandardReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "text",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                ("url", models.URLField(blank=True, default=None, null=True)),
                (
                    "standard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="mvp.compliancestandard",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComplianceStandardComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("ai_types", mvp.models.AITypeChoicesField(default=list)),
                (
                    "rules",
                    models.ManyToManyField(
                        blank=True,
                        related_name="compliance_standard_rules",
                        to="mvp.rule",
                    ),
                ),
                (
                    "standard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="mvp.compliancestandard",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="compliancestandard",
            name="ai_usage",
            field=models.ManyToManyField(
                blank=True, to="mvp.compliancestandardaiusage"
            ),
        ),
        migrations.AddField(
            model_name="compliancestandard",
            name="geographies",
            field=models.ManyToManyField(to="mvp.geography"),
        ),
        migrations.AddField(
            model_name="compliancestandard",
            name="industries",
            field=models.ManyToManyField(to="mvp.industry"),
        ),
        migrations.AddField(
            model_name="organization",
            name="geography",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="mvp.geography",
            ),
        ),
        migrations.AddConstraint(
            model_name="compliancestandardreference",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("url__isnull", False), ("text__isnull", False), _connector="OR"
                ),
                name="mvp_compliancestandardreference_text_or_url",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="compliancestandardcomponent",
            unique_together={("standard", "name")},
        ),
    ]
