# Generated by Django 4.2.4 on 2024-03-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mvp", "0088_compliancestandard_compliancestandardaiusage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="analysis_max_scans",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
