# Generated by Django 4.2.4 on 2024-03-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mvp", "0089_organization_analysis_max_scans"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="geography",
        ),
        migrations.AddField(
            model_name="organization",
            name="geographies",
            field=models.ManyToManyField(to="mvp.geography"),
        ),
    ]
