# Generated by Django 4.2.4 on 2024-03-28 09:43

from django.db import migrations, models
import django.db.models.deletion
import mvp.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0090_remove_organization_geography_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('team_type', models.CharField(blank=True, default=None, help_text='e.g. Inhouse, Offshore', max_length=255, null=True)),
                ('developer_type', models.CharField(blank=True, default=None, help_text='e.g. Junior, Senior', max_length=255, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvp.organization')),
                ('rules', models.ManyToManyField(blank=True, to='mvp.rule')),
            ],
            options={
                'unique_together': {('organization', 'name')},
            },
            bases=(mvp.mixins.PublicIdMixin, models.Model),
        ),
        migrations.AddField(
            model_name='author',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mvp.authorgroup'),
        ),
    ]
