# Generated by Django 4.2.4 on 2024-03-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mvp", "0091_authorgroup_author_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="apply_organization",
            field=models.BooleanField(
                default=False,
                help_text="This rule will apply to the whole organization, including all repository groups and developer groups.",
                verbose_name="Apply at organization level",
            ),
        ),
        migrations.RenameField(
            model_name="rule",
            old_name="display_as_global_rule",
            new_name="is_predefined",
        ),
        migrations.AlterField(
            model_name="rule",
            name="is_predefined",
            field=models.BooleanField(
                default=False,
                help_text="Pre-defined rule by Sema. This is intended to be common rules used by any organization so users don't need to define rules on their own. Users can't modify predefined rules.",
            ),
        ),
    ]
