# Generated by Django 4.2.4 on 2024-04-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mvp", "0092_rename_display_as_global_rule_rule_is_predefined_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rule",
            old_name="is_predefined",
            new_name="is_preset",
        ),
        migrations.AlterField(
            model_name="rule",
            name="is_preset",
            field=models.BooleanField(
                default=False,
                help_text="Preset rule by Sema. This rule will be copied to new organizations when created.",
            ),
        ),
    ]
