# Generated by Django 4.2.4 on 2024-04-01 14:53

from django.db import migrations, models
import mvp.mixins


class Migration(migrations.Migration):
    dependencies = [
        ("mvp", "0094_remove_compliancestandard_geographies_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Geography",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "geographies",
            },
            bases=(mvp.mixins.PublicIdMixin, models.Model),
        ),
        migrations.AddField(
            model_name="compliancestandard",
            name="geographies",
            field=models.ManyToManyField(to="mvp.geography"),
        ),
        migrations.AddField(
            model_name="organization",
            name="geographies",
            field=models.ManyToManyField(to="mvp.geography"),
        ),
    ]
