# Generated by Django 4.2.4 on 2024-04-16 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0096_repository_not_evaluated_num_lines_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='code_ai_blended_num_lines',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='author',
            name='code_ai_blended_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='author',
            name='code_ai_num_lines',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='author',
            name='code_ai_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='author',
            name='code_ai_pure_num_lines',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='author',
            name='code_ai_pure_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='author',
            name='code_num_lines',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='authorgroup',
            name='code_ai_blended_num_lines',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='authorgroup',
            name='code_ai_blended_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='authorgroup',
            name='code_ai_num_lines',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='authorgroup',
            name='code_ai_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='authorgroup',
            name='code_ai_pure_num_lines',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='authorgroup',
            name='code_ai_pure_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='authorgroup',
            name='code_num_lines',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repositorygroup',
            name='code_ai_blended_num_lines',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repositorygroup',
            name='code_ai_blended_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='repositorygroup',
            name='code_ai_num_lines',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repositorygroup',
            name='code_ai_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='repositorygroup',
            name='code_ai_pure_num_lines',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repositorygroup',
            name='code_ai_pure_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='repositorygroup',
            name='code_num_lines',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repositorygroup',
            name='not_evaluated_num_files',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repositorygroup',
            name='not_evaluated_num_lines',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
