# Generated by Django 4.2.11 on 2024-04-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mvp", "0097_author_code_ai_blended_num_lines_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="status_check_enabled",
            field=models.BooleanField(
                default=False, help_text="Enables github status check in PRs"
            ),
        ),
    ]
