# Generated by Django 4.2.4 on 2024-04-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0098_organization_status_check_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='risk',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('strength', 'Strength')], max_length=100),
        ),
    ]
