# Generated by Django 4.2.4 on 2024-04-30 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0099_alter_rule_risk'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositorycommit',
            name='pr_base_commit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mvp.repositorycommit'),
        ),
        migrations.AddField(
            model_name='repositorycommit',
            name='pr_number',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
