# Generated by Django 4.2.11 on 2024-05-06 06:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0100_repositorycommit_pr_base_commit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repositorycommit',
            name='pr_base_commit',
        ),
        migrations.RemoveField(
            model_name='repositorycommit',
            name='pr_number',
        ),
        migrations.CreateModel(
            name='RepositoryPullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_num_lines', models.PositiveIntegerField(default=0)),
                ('code_ai_num_lines', models.PositiveIntegerField(default=0)),
                ('code_ai_blended_num_lines', models.PositiveIntegerField(default=0)),
                ('code_ai_pure_num_lines', models.PositiveIntegerField(default=0)),
                ('code_ai_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('code_ai_blended_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('code_ai_pure_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pr_number', models.PositiveIntegerField()),
                ('base_commit_sha', models.CharField(max_length=40)),
                ('head_commit_sha', models.CharField(max_length=40)),
                ('analysis_num_files', models.PositiveIntegerField(default=0)),
                ('not_evaluated_num_files', models.PositiveIntegerField(default=0)),
                ('not_evaluated_num_lines', models.PositiveIntegerField(default=0)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvp.repository')),
            ],
            options={
                'unique_together': {('repository', 'pr_number')},
            },
        ),
        migrations.AddField(
            model_name='repositorycommit',
            name='pull_requests',
            field=models.ManyToManyField(blank=True, to='mvp.repositorypullrequest'),
        ),
    ]
