# Generated by Django 4.2.11 on 2024-05-06 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mvp", "0101_remove_repositorycommit_pr_base_commit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="jurisdictions_customers",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="jurisdictions_developers",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="jurisdictions_headquarters",
        ),
    ]
