# Generated by Django 4.2.11 on 2024-05-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0103_repositoryfilechunk_code_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoryfilechunk',
            name='code_hash',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=64, null=True),
        ),
    ]
