# Generated by Django 4.2.11 on 2024-06-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mvp", "0104_alter_repositoryfilechunk_code_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="repositorypullrequest",
            name="is_closed",
            field=models.BooleanField(default=False),
        ),
    ]
