# Generated by Django 4.2.11 on 2024-06-05 00:16

from django.db import migrations, models
from django.db.migrations.operations import RunPython


def copy_installation_id(apps, schema_editor):
    Repository = apps.get_model("mvp", "Repository")
    repos = Repository.objects.filter(installation_id__isnull=False)
    for repo in repos:
        id = repo.installation_id
        repo.external_data = {"installation_id": id} if id != 0 else {"manual": True}
        repo.save()


def reverse_copy_installation_id(apps, schema_editor):
    Repository = apps.get_model("mvp", "Repository")
    repos = Repository.objects.filter(external_data__isnull=False)
    for repo in repos:
        is_manual = repo.external_data.get("manual", False)
        id = repo.external_data.get("installation_id", None) if not is_manual else 0
        repo.installation_id = id
        repo.save()


class Migration(migrations.Migration):

    dependencies = [
        ("mvp", "0105_repositorypullrequest_is_closed"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="external_data",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        RunPython(copy_installation_id, reverse_copy_installation_id),
        migrations.RemoveField(
            model_name="repository",
            name="installation_id",
        ),
    ]
