# Generated by Django 4.2.11 on 2024-06-25 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0106_repository_installation_id_to_external_data__manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_file_path', models.CharField(max_length=500)),
                ('response_status_code', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('response_message', models.TextField(blank=True, default=None, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvp.dataprovider')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
