# Generated by Django 4.2.11 on 2024-07-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0107_webhookrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_software_company',
            field=models.BooleanField(default=False, help_text='Is your organization a software company?'),
        ),
    ]
