# Generated by Django 4.2.11 on 2024-07-19 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0108_organization_is_software_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryPullRequestStatusCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_check_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True, default=None, help_text='The markdown message', null=True)),
                ('external_data', models.JSONField(blank=True, default=dict, null=True)),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvp.repositorypullrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
