# Generated by Django 4.2.11 on 2024-08-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0109_repositorypullrequeststatuscheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositorycommit',
            name='analysis_metadata',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
