# Generated by Django 4.2.11 on 2024-08-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0110_repositorycommit_analysis_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositorycommit',
            name='last_attested_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='repositorycommit',
            name='last_recalculated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='repositoryfile',
            name='last_attested_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='repositoryfile',
            name='last_recalculated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='repositorypullrequest',
            name='last_attested_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='repositorypullrequest',
            name='last_recalculated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
