# Generated by Django 4.2.11 on 2024-08-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0111_repositorycommit_last_attested_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='status_check_mark_as_failed',
            field=models.BooleanField(default=False, help_text='Mark status check as failed if the GenAI rules are not met'),
        ),
    ]
