# Generated by Django 4.2.11 on 2024-08-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mvp", "0113_organization_analysis_historic_enabled_and_more__manual"),
    ]

    operations = [
        migrations.AddField(
            model_name="repositorycommit",
            name="languages",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="status_check_enabled",
            field=models.BooleanField(
                default=False, help_text="Enables status check in PRs feature"
            ),
        ),
    ]
