# Generated by Django 4.2.11 on 2024-08-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mvp", "0114_repositorycommit_languages_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="repositoryfile",
            index=models.Index(
                fields=["not_evaluated", "file_path"],
                name="mvp_reposit_not_eva_36754f_idx",
            ),
        ),
    ]
