# Generated by Django 4.2.11 on 2024-08-30 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mvp", "0115_repositoryfile_mvp_reposit_not_eva_36754f_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="repositorygroup",
            name="max_genai_code_usage_percentage",
            field=models.IntegerField(
                default=20,
                help_text="Maximum GenAI Code Usage",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="repositorygroup",
            name="potential_productivity_improvement_label",
            field=models.CharField(
                choices=[
                    ("unselected", "Unset"),
                    ("new_codebase", "New Codebase"),
                    (
                        "existing_codebase_new_features",
                        "Existing Codebase - Primarily New Features and Functionality",
                    ),
                    (
                        "existing_codebase_tech_debt",
                        "Existing Codebase - Primarily Tech Debt Reduction",
                    ),
                    (
                        "existing_codebase_bug_fixes",
                        "Existing Codebase - Primarily Bug Fixes",
                    ),
                    (
                        "existing_codebase_prototyping",
                        "Existing Codebase - Primarily Prototyping",
                    ),
                ],
                default="unselected",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="repositorygroup",
            name="potential_productivity_improvement_percentage",
            field=models.IntegerField(
                default=0,
                help_text="Estimated % of potential productivity improvement",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="repositorygroup",
            name="time_spent_coding_percentage",
            field=models.IntegerField(
                default=30,
                help_text="Estimated % of time spent coding",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
