# Generated by Django 4.2.11 on 2024-09-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mvp", "0116_repositorygroup_max_genai_code_usage_percentage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="reason_for_measuring_genai",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "increase_roi",
                        "Increase the Return on Investment (ROI) of using GenAI coding tools",
                    ),
                    ("legal_compliance", "Meet Legal and/or Compliance requirements"),
                    (
                        "board_investor_requirements",
                        "Meet Board of Director and/or future Investor/Acquirer requirements",
                    ),
                    ("other", "Other"),
                ],
                default=None,
                max_length=100,
                null=True,
            ),
        ),
    ]
