# Generated by Django 4.2.11 on 2024-08-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mvp", "0117_organization_reason_for_measuring_genai"),
    ]

    operations = [
        migrations.AddField(
            model_name="repositoryfile",
            name="chunks_ai_blended",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="repositoryfile",
            name="chunks_ai_pure",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="repositoryfile",
            name="chunks_attested",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="repositoryfile",
            name="chunks_human",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="repositoryfile",
            name="chunks_not_evaluated",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
