# Generated by Django 4.2.11 on 2024-09-17 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mvp", "0118_repositoryfile_chunks_ai_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="company_number_of_developers",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Collected at sign up. If None then user signed up before this field was added or the user was invited.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="company_url",
            field=models.URLField(
                blank=True,
                help_text="Collected at sign up. If None then user signed up before this field was added or the user was invited.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_organizations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
