# Generated by Django 4.2.11 on 2024-10-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mvp", "0121_alter_repositoryfile_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="first_email_sent",
            field=models.BooleanField(
                default=False, help_text="first analysis started email sent"
            ),
        ),
    ]
