# Generated by Django 4.2.11 on 2024-10-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mvp", "0122_organization_first_email_sent"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "starts_at",
                    models.DateTimeField(
                        help_text="When to start showing this message to users"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When to stop showing this message to users"
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="The message to show to users. Up to 200 characters",
                        max_length=200,
                    ),
                ),
                (
                    "read_more_link",
                    models.URLField(
                        blank=True,
                        default=None,
                        help_text="Optional external link for more information",
                        null=True,
                    ),
                ),
                (
                    "is_dismissible",
                    models.BooleanField(
                        default=True,
                        help_text="Whether or not users can hide this message",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
