# Generated by Django 4.2.11 on 2024-10-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mvp", "0123_systemmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="consent_marketing_notifications",
            field=models.BooleanField(
                default=False,
                help_text="Whether or not the user consented to receive marketing notifications. This is necessary for SOC2 compliance. Do not change this without the user's consent.",
            ),
        ),
    ]
