# Generated by Django 4.2.11 on 2024-10-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mvp", "0124_customuser_consent_marketing_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="avg_dev_annual_work_hours",
            field=models.PositiveIntegerField(
                default=1500, help_text="Average hours worked by a developer annually"
            ),
        ),
        migrations.AddField(
            model_name="repositorygroup",
            name="num_developers",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Number of developers"
            ),
        ),
    ]
