# Generated by Django 4.2.11 on 2024-10-15 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def add_current_password_to_history(apps, schema_editor):
    CustomUser = apps.get_model(settings.AUTH_USER_MODEL)
    PasswordHistory = apps.get_model("mvp", "PasswordHistory")
    for user in CustomUser.objects.all():
        if user.password:
            PasswordHistory.objects.create(user=user, password=user.password)


class Migration(migrations.Migration):

    dependencies = [
        ("mvp", "0126_remove_organization_app_flags__manual"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
