# Generated by Django 4.2.11 on 2024-10-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mvp", "0127_passwordhistory__manual"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="require_mfa",
            field=models.BooleanField(
                default=False,
                help_text="Require MFA for all users in this organization",
            ),
        ),
    ]
