# Generated by Django 4.2.16 on 2024-10-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mvp", "0128_organization_require_mfa"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="tools_genai_monthly_cost",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Monthly Cost of GenAI Tool(s) per Developer",
            ),
        ),
    ]
