# Generated by Django 4.2.16 on 2024-11-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mvp", "0130_alter_repositoryfile_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="split",
            field=models.BooleanField(
                default=False,
                help_text="When true, means the author was manually split and will not be automatically linked",
            ),
        ),
    ]
