# Generated by Django 4.2.16 on 2024-12-04 14:47

from django.db import migrations, models
import django.db.models.deletion
import timescale.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("mvp", "0131_author_split"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    timescale.db.models.fields.TimescaleDateTimeField(interval="1 day"),
                ),
                ("code_num_lines", models.PositiveIntegerField(default=0)),
                ("code_ai_num_lines", models.PositiveIntegerField(default=0)),
                ("code_ai_blended_num_lines", models.PositiveIntegerField(default=0)),
                ("code_ai_pure_num_lines", models.PositiveIntegerField(default=0)),
                ("code_not_ai_num_lines", models.PositiveIntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mvp.author"
                    ),
                ),
                (
                    "commit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mvp.repositorycommit",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mvp.repository"
                    ),
                ),
            ],
            options={
                "unique_together": {("author", "commit", "time")},
            },
        ),
    ]
