# Generated by Django 4.2.17 on 2024-12-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mvp", "0132_authorstat"),
    ]

    operations = [
        migrations.AddField(
            model_name="repositorycommit",
            name="shredded",
            field=models.BooleanField(
                default=False, help_text="Whether the source code has been shredded"
            ),
        ),
    ]
