# Generated by Django 4.2.16 on 2025-01-08 15:36

from django.db import migrations, models
import mvp.models


class Migration(migrations.Migration):

    dependencies = [
        ("mvp", "0133_repositorycommit_shredded"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="compass_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether or not Compass is enabled for this organization",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="reasons_for_measuring_genai",
            field=mvp.models.ReasonForMeasuringGenAIChoicesField(
                blank=True, default=list, null=True
            ),
        ),
    ]
