# Generated by Django 4.2.16 on 2025-02-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mvp", "0134_organization_compass_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="compass_anomaly_insights_notifications",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the user has opted in to receive anomaly insights notifications from Compass.",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="compass_summary_insights_notifications",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the user has opted in to receive summary insights notifications from Compass.",
            ),
        ),
    ]
