# Generated by Django 4.2.16 on 2025-02-24 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mvp", "0135_customuser_compass_anomaly_insights_notifications_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="compass_enabled",
        ),
    ]
