# Generated by Django 4.2.16 on 2025-02-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mvp", "0136_remove_organization_compass_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="onboarding_completed",
            field=models.BooleanField(default=False),
        ),
    ]
