# Generated by Django 4.2.16 on 2025-03-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mvp", "0137_organization_onboarding_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="contextualization_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the contextualization script is to be run for this organization",
            ),
        ),
    ]
