# Generated by Django 4.2.16 on 2025-03-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mvp", "0138_organization_contextualization_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="organizations",
            field=models.ManyToManyField(blank=True, to="mvp.organization"),
        ),
    ]
