# Generated by Django 4.2.16 on 2025-03-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mvp", "0139_alter_customuser_organizations"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organization",
            name="marked_for_deletion",
            field=models.BooleanField(
                default=False,
                help_text="Marks the organization for deletion before the nightly scan",
            ),
        ),
    ]
