# Generated by Django 4.2.16 on 2025-03-18 15:15

import cto_tool.storages
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("mvp", "0140_organization_deleted_at_organization_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="initials",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=cto_tool.storages.get_s3_storage,
                upload_to="profile_images",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_image_thumbnail",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True,
                null=True,
                storage=cto_tool.storages.get_s3_storage,
                upload_to="profile_images",
            ),
        ),
    ]
