# Generated by Django 4.2.16 on 2025-04-29 10:08

from django.db import migrations, models
import django.db.models.deletion
import mvp.mixins


class Migration(migrations.Migration):

    dependencies = [
        ("mvp", "0141_customuser_initials_customuser_profile_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JiraProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("key", models.CharField(max_length=255)),
                ("external_id", models.CharField(max_length=100)),
                ("is_selected", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mvp.organization",
                    ),
                ),
                (
                    "repository_group",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mvp.repositorygroup",
                    ),
                ),
            ],
            options={
                "unique_together": {("organization", "external_id")},
            },
            bases=(mvp.mixins.PublicIdMixin, models.Model),
        ),
    ]
