# Generated by Django 4.2.16 on 2025-05-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mvp", "0142_jiraproject"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jiraproject",
            name="repository_group",
        ),
        migrations.AddField(
            model_name="jiraproject",
            name="repository_group",
            field=models.ManyToManyField(blank=True, to="mvp.repositorygroup"),
        ),
    ]
