# Generated by Django 4.2.16 on 2025-05-30 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mvp", "0143_remove_jiraproject_repository_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataproviderconnection",
            name="connected_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="dataproviderconnection",
            name="connected_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
