# Generated by Django 4.2.23 on 2025-07-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mvp", "0145_repository_default_branch_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="hide_environment_banner",
            field=models.BooleanField(default=False),
        ),
    ]
