# Generated by Django 4.2.23 on 2025-07-25 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mvp", "0146_customuser_hide_environment_banner"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("data", models.JSONField(blank=True, default=None, null=True)),
                (
                    "service",
                    models.CharField(
                        blank=True,
                        choices=[("teams", "Microsoft Teams")],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "connected_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "connected_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mvp.organization",
                    ),
                ),
            ],
            options={
                "unique_together": {("organization", "service")},
            },
        ),
    ]
