# Generated by Django 4.2.23 on 2025-08-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mvp", "0148_migrate_users_to_new_role_system__manual"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="userinvitation",
            name="is_deleted",
        ),
        migrations.AddField(
            model_name="organization",
            name="restored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="transaction_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userinvitation",
            name="restored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userinvitation",
            name="transaction_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
