# Generated by Django 4.2.23 on 2025-08-21 13:07

from django.db import migrations, models


def migrate_repository_group_to_repository_groups(apps, schema_editor):
    Repository = apps.get_model("mvp", "Repository")
    ThroughModel = Repository.repository_group.through

    relations = [
        ThroughModel(repository_id=repository_id, repositorygroup_id=group_id)
        for repository_id, group_id in Repository.objects.exclude(group__isnull=True)
        .values_list("id", "group_id")
        .iterator()
    ]

    ThroughModel.objects.bulk_create(relations, ignore_conflicts=True)


def reverse_migrate_repository_group_to_repository_groups(apps, schema_editor):
    Repository = apps.get_model("mvp", "Repository")
    ThroughModel = Repository.repository_group.through

    repositories = [
        Repository(id=repository_id, group_id=group_id)
        for repository_id, group_id in ThroughModel.objects.values_list(
            "repository_id", "repositorygroup_id"
        ).iterator()
    ]

    Repository.objects.bulk_update(repositories, ["group_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("mvp", "0149_remove_organization_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="repository_group",
            field=models.ManyToManyField(blank=True, related_name="repositories", to="mvp.repositorygroup"),
        ),
        migrations.AlterField(
            model_name="jiraproject",
            name="repository_group",
            field=models.ManyToManyField(blank=True, related_name="jira_projects", to="mvp.repositorygroup"),
        ),
        migrations.RunPython(
            migrate_repository_group_to_repository_groups,
            reverse_migrate_repository_group_to_repository_groups,
        ),
        migrations.RemoveField(
            model_name="repository",
            name="group",
        ),
    ]
