# Generated by Django 4.2.16 on 2025-05-09 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mvp", "0142_jiraproject"),
    ]

    operations = [
        migrations.CreateModel(
            name="Initiative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("justification", models.TextField(null=True)),
                (
                    "percentage",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "percentage_tickets_done",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("tickets_done", models.IntegerField(default=0)),
                ("tickets_total", models.IntegerField(default=0)),
                ("start_date", models.CharField(max_length=255, null=True)),
                ("estimated_end_date", models.CharField(max_length=255, null=True)),
                ("estimated_end_date_insights", models.TextField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Roadmap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("summary", models.TextField(null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "day_interval",
                    models.IntegerField(
                        choices=[(1, "One day"), (7, "One week"), (14, "Two weeks")]
                    ),
                ),
                ("raw_roadmap", models.JSONField(null=True)),
                ("raw_roadmap_reconciliation", models.JSONField(null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roadmaps",
                        to="mvp.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReconcilableInitiative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("initiative_type", models.CharField(max_length=255, null=True)),
                ("git_activity", models.TextField(null=True)),
                ("jira_activity", models.TextField(null=True)),
                (
                    "roadmap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconcilable_initiatives",
                        to="contextualization.roadmap",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InitiativeEpic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(null=True)),
                ("percentage", models.FloatField(default=0)),
                (
                    "initiative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="epics",
                        to="contextualization.initiative",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="initiative",
            name="roadmap",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="initiatives",
                to="contextualization.roadmap",
            ),
        ),
    ]
