# Generated by Django 4.2.16 on 2025-05-15 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mvp", "0143_remove_jiraproject_repository_group_and_more"),
        ("contextualization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("raw_json", models.JSONField()),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mvp.organization",
                    ),
                ),
            ],
            options={
                "unique_together": {("organization", "date")},
            },
        ),
    ]
