# Generated by Django 4.2.16 on 2025-05-19 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mvp", "0143_remove_jiraproject_repository_group_and_more"),
        ("contextualization", "0002_dailymessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "day_interval",
                    models.IntegerField(
                        choices=[(1, "One day"), (7, "One week"), (14, "Two weeks")]
                    ),
                ),
                (
                    "attention_level",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("attention_level_ceo", "CEO"),
                            ("attention_level_cto_or_cpo", "CTO or CPO"),
                            (
                                "attention_level_director_or_manager",
                                "Director or Manager",
                            ),
                            ("attention_level_team_lead", "Team Lead"),
                        ],
                        max_length=108,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mvp.organization",
                    ),
                ),
                (
                    "repository_groups",
                    models.ManyToManyField(blank=True, to="mvp.repositorygroup"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("organization", "user", "day_interval")},
            },
        ),
    ]
