# Generated by Django 4.2.16 on 2025-06-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contextualization", "0003_messagefilter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="initiative",
            name="estimated_end_date_insights",
        ),
        migrations.AddField(
            model_name="initiative",
            name="delivery_estimate",
            field=models.JSONField(null=True),
        ),
    ]
