# Generated by Django 4.2.21 on 2025-06-24 11:33

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("contextualization", "0005_message_filter_significance_score__manual"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagefilter",
            name="ticket_categories",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("Bug", "Bug"),
                    ("Story", "Story"),
                    ("Incident", "Incident"),
                    ("Request", "Request"),
                    ("Manual Testing", "Manual Testing"),
                    ("Automated Testing", "Automated Testing"),
                    ("Other", "Other"),
                ],
                default=list,
                max_length=65,
            ),
        ),
    ]
