# Generated by Django 4.2.23 on 2025-07-03 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mvp", "0145_repository_default_branch_name"),
        ("contextualization", "0006_messagefilter_ticket_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketCompleteness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ticket_id", models.CharField(max_length=255)),
                ("name", models.TextField()),
                ("description", models.TextField(null=True)),
                ("status", models.TextField(null=True)),
                ("assignee", models.TextField(null=True)),
                ("reporter", models.TextField(null=True)),
                ("priority", models.TextField(null=True)),
                ("completeness_score", models.IntegerField()),
                ("raw_completeness_score_evaluation", models.TextField()),
                ("completeness_score_explanation", models.TextField()),
                (
                    "llm_category",
                    models.TextField(
                        choices=[
                            ("Bug", "Bug"),
                            ("Story", "Story"),
                            ("Incident", "Incident"),
                            ("Request", "Request"),
                            ("Manual Testing", "Manual Testing"),
                            ("Automated Testing", "Automated Testing"),
                            ("Other", "Other"),
                        ]
                    ),
                ),
                ("stage", models.TextField()),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mvp.jiraproject",
                    ),
                ),
            ],
            options={
                "unique_together": {("ticket_id", "project_id", "date")},
            },
        ),
    ]
