# Generated by Django 4.2.23 on 2025-07-09 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mvp", "0145_repository_default_branch_name"),
        (
            "contextualization",
            "0008_tecketcompleteness_add_quality_category_remove_status__manual",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="roadmap",
            name="repository_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roadmaps",
                to="mvp.repositorygroup",
            ),
        ),
    ]
