# Generated by Django 4.2.23 on 2025-07-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contextualization", "0009_roadmap_repository_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="initiative",
            name="custom_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="initiative",
            name="disabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="initiative",
            name="pinned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="initiativeepic",
            name="custom_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="initiativeepic",
            name="disabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="initiativeepic",
            name="pinned",
            field=models.BooleanField(default=False),
        ),
    ]
