# Generated by Django 4.2.23 on 2025-07-18 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contextualization", "0011_anomalyinsights"),
    ]

    operations = [
        migrations.AddField(
            model_name="initiative",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="contextualization.initiative",
            ),
        ),
        migrations.AddField(
            model_name="initiativeepic",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="contextualization.initiativeepic",
            ),
        ),
    ]
