# Generated by Django 4.2.4 on 2024-02-16 13:13

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mvp.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenAIFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_line_start', models.PositiveIntegerField()),
                ('code_line_end', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pure', 'Pure'), ('blended', 'Blended'), ('human', 'Human')], max_length=10)),
                ('vote', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True, default='')),
                ('content_hash', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('file_path', models.CharField(max_length=255)),
                ('file', models.FileField(storage=api.models.OverwriteStorage(), upload_to=api.models.GenAIFeedback.get_filename_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GenAI Feedback',
                'verbose_name_plural': 'GenAI Feedbacks',
                'ordering': ['-created_at'],
            },
            bases=(models.Model, mvp.mixins.PublicIdMixin),
        ),
    ]
