llms:
  default_llm: "claude"
  big_text_llm: "gemini"
  claude:
    model: "claude-sonnet-4-20250514"
    token_limit: 170000
    batch_threshold: 650000
    requests_per_second: 15
    temperature: 0.1
  gemini:
    model: "gemini-2.5-pro-preview-06-05"
    token_limit: 950000
    batch_threshold: 1800000
    temperature: 0.1
    requests_per_second: 10
