# Generated by Django 4.2.16 on 2025-02-17 12:15

from django.db import migrations, models
import django.db.models.deletion
import timescale.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mvp", "0134_organization_compass_enabled_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitDiffContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    timescale.db.models.fields.TimescaleDateTimeField(interval="1 day"),
                ),
                ("sha", models.CharField(max_length=40)),
                ("file_path", models.CharField(max_length=500)),
                ("git_diff_hash", models.CharField(max_length=64)),
                ("category", models.CharField(max_length=255)),
                ("summary", models.TextField()),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mvp.repository"
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("repository", "sha", "file_path", "git_diff_hash", "time")
                },
            },
        ),
    ]
