# Generated by Django 4.2.16 on 2025-02-28 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mvp", "0137_organization_onboarding_completed"),
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gitdiffcontext",
            name="description_of_maintenance_relevance",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="gitdiffcontext",
            name="impact_on_product",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="gitdiffcontext",
            name="maintenance_relevance",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="gitdiffcontext",
            name="purpose_of_change",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="gitdiffcontext",
            name="summary",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name="GitDiffRepositoryGroupInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(blank=True, default=None, null=True)),
                ("end_date", models.DateField(blank=True, default=None, null=True)),
                ("category", models.CharField(max_length=255)),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "justification",
                    models.TextField(blank=True, default=None, null=True),
                ),
                ("examples", models.TextField(blank=True, default=None, null=True)),
                ("generated", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mvp.organization",
                    ),
                ),
                (
                    "repository_group",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mvp.repositorygroup",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("repository_group", "start_date", "end_date", "category")
                },
            },
        ),
    ]
